SQL_FILE_PATH = 'projects/boxscore/sql_files'
DDL_FILE_PATH = 'projects/boxscore/sql_files/ddls'
WORKING_FILE_PATH = '/mnt/data/working/boxscore'
ARCHIVE_FILE_PATH = '/mnt/data/archive/boxscore'

PLAYER_FIELDS = ["game_id",
                 "team_id",
                 "player_id",
                 "start_position",
                 "min",
                 "fgm",
                 "fga",
                 "fg_pct",
                 "fg3m",
                 "fg3a",
                 "fg3_pct",
                 "ftm",
                 "fta",
                 "ft_pct",
                 "oreb",
                 "dreb",
                 "reb",
                 "ast",
                 "stl",
                 "blk",
                 "to",
                 "pf",
                 "pts",
                 "plus_minus"]

TEAM_FIELDS = ["game_id",
               "team_id",
               "team_name",
               "team_abbreviation",
               "team_city",
               "min",
               "fgm",
               "fga",
               "fg_pct",
               "fg3m",
               "fg3a",
               "fg3_pct",
               "ftm",
               "fta",
               "ft_pct",
               "oreb",
               "dreb",
               "reb",
               "ast",
               "stl",
               "blk",
               "to",
               "pf",
               "pts",
               "plus_minus"]
