resources = 'projects/boxscore/resources'
ddl = f'{resources}/ddls'

players_fields = ["game_id",
                  "team_id",
                  "player_id",
                  "start_position",
                  "min",
                  "fgm",
                  "fga",
                  "fg_pct",
                  "fg3m",
                  "fg3a",
                  "fg3_pct",
                  "ftm",
                  "fta",
                  "ft_pct",
                  "oreb",
                  "dreb",
                  "reb",
                  "ast",
                  "stl",
                  "blk",
                  "to",
                  "pf",
                  "pts",
                  "plus_minus"]

team_fields = ["game_id",
               "team_id",
               "team_name",
               "team_abbreviation",
               "team_city",
               "min",
               "fgm",
               "fga",
               "fg_pct",
               "fg3m",
               "fg3a",
               "fg3_pct",
               "ftm",
               "fta",
               "ft_pct",
               "oreb",
               "dreb",
               "reb",
               "ast",
               "stl",
               "blk",
               "to",
               "pf",
               "pts",
               "plus_minus"]
