insert into working_nba_teams_st
    (
        team_id,
        team_name,
        abbr,
        city,
        state,
        latitude,
        longitude
    )
values
    (
        "{team_id}",
        "{team_name}",
        "{abbr}",
        "{city}",
        "{state}",
        "{latitude}",
        "{longitude}"
    )
;