create table if not exists working_boxscore_team_st(
    game_id int,
    team_id int,
    team_name string,
    team_abbreviation string,
    team_city string,
    min int,
    fgm int,
    fga int,
    fg_pct int,
    fg3m int,
    fg3a int,
    fg3_pct int,
    ftm int,
    fta int,
    ft_pct int,
    oreb int,
    dreb int,
    reb int,
    ast int,
    stl int,
    blk int,
    "to" int,
    pf int,
    pts int,
    plus_minus string
);